"""back

Revision ID: 061eed8a8a3f
Revises: 
Create Date: 2025-07-24 18:31:42.602932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app
import app.core
import app.core.database


# revision identifiers, used by Alembic.
revision: str = '061eed8a8a3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', app.core.database.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.core.database.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.database.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.core.database.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.create_table('sizes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('M', 'L', 'XL', 'XXL', name='sizeenum'), nullable=False),
    sa.Column('created_at', app.core.database.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.core.database.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('created_at', app.core.database.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.core.database.TZDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', app.core.database.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.core.database.TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_carts_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', name='statusenum'), nullable=False),
    sa.Column('receiver_name', sa.String(length=50), nullable=False),
    sa.Column('receiver_phone', sa.String(length=15), nullable=False),
    sa.Column('receiver_email', sa.String(length=255), nullable=False),
    sa.Column('shipping_city', sa.String(length=50), nullable=False),
    sa.Column('shipping_street', sa.String(length=255), nullable=False),
    sa.Column('payment_method', sa.Enum('CARD', 'COD', name='paymentmethod'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', app.core.database.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.core.database.TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_orders_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', app.core.database.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.core.database.TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_product_images_product_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productsizes',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('size_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.database.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.core.database.TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_products_sizes_product_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], name='fk_products_sizes_sizes_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'size_id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('size_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=False),
    sa.Column('created_at', app.core.database.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.core.database.TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name='fk_cart_items_cart_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_cart_items_product_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], name='fk_cart_items_size_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('size_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=False),
    sa.Column('created_at', app.core.database.TZDateTime(), nullable=False),
    sa.Column('updated_at', app.core.database.TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_order_items_order_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_order_items_product_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], name='fk_order_items_sizes_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('cart_items')
    op.drop_table('productsizes')
    op.drop_table('product_images')
    op.drop_table('orders')
    op.drop_table('carts')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sizes')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_table('admins')
    # ### end Alembic commands ###
