"""empty message

Revision ID: 3b3c4ffb768e
Revises: 53982618bcda
Create Date: 2025-07-17 13:08:10.662939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3c4ffb768e'
down_revision: Union[str, None] = '53982618bcda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('receiver_name', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('receiver_phone', sa.String(length=15), nullable=False))
    op.add_column('orders', sa.Column('receiver_email', sa.String(length=255), nullable=False))
    op.alter_column('orders', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('orders', 'shipping_country')
    op.drop_column('orders', 'post_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('post_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('shipping_country', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.alter_column('orders', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('orders', 'receiver_email')
    op.drop_column('orders', 'receiver_phone')
    op.drop_column('orders', 'receiver_name')
    # ### end Alembic commands ###
