"""Change cart item columns

Revision ID: 53982618bcda
Revises: b54fde6b2e26
Create Date: 2025-07-11 11:47:11.214034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53982618bcda'
down_revision: Union[str, None] = 'b54fde6b2e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('thumbnail', sa.String(), nullable=False))
    op.drop_column('cart_items', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('cart_items', 'thumbnail')
    # ### end Alembic commands ###
