"""Add product size, size and change order db with little other adjustments

Revision ID: a21afea5be4a
Revises: b468cf1fb756
Create Date: 2025-07-09 20:12:43.970210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a21afea5be4a'
down_revision: Union[str, None] = 'b468cf1fb756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
payment_method_enum = sa.Enum('CARD', 'COD', name='paymentmethod')
payment_status_enum = sa.Enum('PENDING', 'PAID', 'REFUNDED', name='paymentstatus')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sizes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('M', 'L', 'XL', 'XXL', name='sizeenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('productsizes',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('size_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'size_id')
    )
    op.add_column('orders', sa.Column('shipping_country', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('shipping_city', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('shipping_street', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('post_index', sa.Integer(), nullable=False))
    payment_method_enum.create(op.get_bind())
    payment_status_enum.create(op.get_bind())
    op.add_column('orders', sa.Column('payment_method', sa.Enum('CARD', 'COD', name='paymentmethod'), nullable=False))
    op.add_column('orders', sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'REFUNDED', name='paymentstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'post_index')
    op.drop_column('orders', 'shipping_street')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_country')
    op.drop_table('productsizes')
    op.drop_table('sizes')
    # ### end Alembic commands ###
