"""adjusted CartItem and Size

Revision ID: b54fde6b2e26
Revises: a21afea5be4a
Create Date: 2025-07-10 22:34:33.161545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54fde6b2e26'
down_revision: Union[str, None] = 'a21afea5be4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('size_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'cart_items', 'sizes', ['size_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'size_id')
    # ### end Alembic commands ###
