"""Adjust order and order items

Revision ID: dfd0a0142287
Revises: 3b3c4ffb768e
Create Date: 2025-07-21 12:00:04.431318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd0a0142287'
down_revision: Union[str, None] = '3b3c4ffb768e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('size_id', sa.UUID(), nullable=False))
    op.add_column('order_items', sa.Column('thumbnail', sa.String(), nullable=False))
    op.create_foreign_key(None, 'order_items', 'sizes', ['size_id'], ['id'], ondelete='CASCADE')
    op.drop_column('order_items', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'thumbnail')
    op.drop_column('order_items', 'size_id')
    # ### end Alembic commands ###
